//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImagenProducto
    {
        public int ImagenProductoID { get; set; }
        public short Tipo { get; set; }
        public string Url { get; set; }
        public int ProductoID { get; set; }
    
        public virtual Producto Producto { get; set; }
    }
}
