//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductoSimbolo
    {
        public int ProductoSimboloID { get; set; }
        public string NombreSimbolo { get; set; }
        public string DescripcionSimbolo { get; set; }
        public string CaracteristicasSimbolo { get; set; }
        public string ImagenPortadaSimbolo { get; set; }
        public bool Estatus { get; set; }
    }
}
