//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductoDibujosAnimados
    {
        public int ProductoDibujosAnimadosID { get; set; }
        public string NombreDibujo { get; set; }
        public string DescripcionDibujo { get; set; }
        public string CaracteristicasDibujo { get; set; }
        public string ImagenPortadaDibujo { get; set; }
        public bool Estatus { get; set; }
    }
}
