//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductoFigurasGeometricas
    {
        public int ProductoFiguraID { get; set; }
        public string NombreFigura { get; set; }
        public string DescripcionFigura { get; set; }
        public string CaracteristicasFigura { get; set; }
        public string ImagenPortadaFigura { get; set; }
        public bool Estatus { get; set; }
    }
}
