//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicesCNC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedidos
    {
        public int pedidoID { get; set; }
        public int productoID { get; set; }
        public int contactoID { get; set; }
        public System.DateTime fechapedido { get; set; }
        public Nullable<System.DateTime> fechaentrega { get; set; }
        public int cantidad { get; set; }
        public Nullable<int> dimension1 { get; set; }
        public Nullable<int> dimension2 { get; set; }
        public string unidadmedida { get; set; }
    
        public virtual Contactos Contactos { get; set; }
        public virtual Contactos Contactos1 { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
