//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicesCNC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductoArchivos
    {
        public int archivoID { get; set; }
        public int productoID { get; set; }
        public string tipoarchivo { get; set; }
        public string archivourl { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual Productos Productos { get; set; }
    }
}
