//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicesCNC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public int usuarioID { get; set; }
        public string usuario { get; set; }
        public string contrasenia { get; set; }
        public string nombre { get; set; }
        public string apellidos { get; set; }
        public string correoelectronico { get; set; }
        public int rolID { get; set; }
        public bool estatus { get; set; }
    
        public virtual Roles Roles { get; set; }
    }
}
