//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicesCNC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwProductosArchivo
    {
        public int archivoID { get; set; }
        public string archivourl { get; set; }
        public int productoID { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> categoriaID { get; set; }
        public string categoria { get; set; }
    }
}
